---

# Yum
- name: Install GnuPG (Yum)
  yum: pkg=gnupg state=present
  when: ansible_pkg_mgr == 'yum'

# Homebrew
- name: Install GnuPG (Homebrew)
  homebrew: name=gnupg2 state=present
  become: true
  become_user: "{{ gnupg_homebrew_user }}"
  when: ansible_pkg_mgr == 'homebrew'

# Other package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Homebrew or Yum are supported)"
  when: ansible_pkg_mgr != 'yum' and ansible_pkg_mgr != 'homebrew'
