---

# Yum
- name: Install GnuPG (Yum)
  yum:
    pkg: gnupg
    state: present
  tags: [ gnupg ]
  when: ansible_pkg_mgr == 'yum'

# Homebrew
- name: Install GnuPG (Homebrew)
  homebrew:
    name: gnupg
    state: present
  become: true
  become_user: "{{ gnupg_homebrew_user }}"
  tags: [ gnupg ]
  when: ansible_pkg_mgr == 'homebrew'

# Other package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Homebrew or Yum are supported)"
  tags: [ gnupg ]
  when: ansible_pkg_mgr != 'yum' and ansible_pkg_mgr != 'homebrew'

- name: Create gnupg configuration directory
  file:
    path: "{{ gnupg_config_directory }}"
    owner: "{{ gnupg_user }}"
    group: "{{ gnupg_group }}"
    mode: 0700
    state: directory
  tags: [ gnupg ]

- name: Configure gpg
  template:
    src: gpg.conf
    dest: "{{ gnupg_config_file }}"
    owner: "{{ gnupg_user }}"
    group: "{{ gnupg_group }}"
  tags: [ gnupg ]

- name: Configure gpg-agent
  template:
    src: gpg-agent.conf
    dest: "{{ gnupg_agent_config_file }}"
    owner: "{{ gnupg_user }}"
    group: "{{ gnupg_group }}"
  tags: [ gnupg ]
